name: deploy website
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploying
        run: now -t uTjiMesILjANiKGX1SdIqEDJ -c --prod --name=shivam 
        
         
