name: deploy website
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploying 
        working-directory: ./shivam
        run: vercel -t uTjiMesILjANiKGX1SdIqEDJ -c --prod --name=shivam 
        
         
