name: deploy website
on: workflow_dispatch
  #inputs:
   #  urlname:
    # required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploying 
        working-directory: ./krishna
        run: vercel -t uTjiMesILjANiKGX1SdIqEDJ -c --prod --name=krishna && vercel -t uTjiMesILjANiKGX1SdIqEDJ domain add krishna.launchmysite.in 


        
         
